CREATE SCHEMA DEV_V
COMMENT = 'This schema will hold all RAW views';

--Checking successful schema creation
SHOW SCHEMAS;

--Normal View
CREATE VIEW DEV.DEV_V.date_wise_orders
AS
SELECT L_COMMITDATE AS ORDER_DATE,
SUM(L_QUANTITY) AS TOT_QTY,
SUM(L_EXTENDEDPRICE) AS TOT_PRICE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM
GROUP BY L_COMMITDATE;
-- Took 2s to create, 41s to query.

--Materialized View:
CREATE MATERIALIZED VIEW DEV.DEV_V.date_wise_orders_fast
AS
SELECT L_COMMITDATE AS ORDER_DATE,
SUM(L_QUANTITY) AS TOT_QTY,
SUM(L_EXTENDEDPRICE) AS TOT_PRICE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM
GROUP BY L_COMMITDATE;
-- Took 1m to create, 1.4s to query.